services:
  db:
    image: mysql:8.0.37
    restart: always
    volumes:
      - ./docker/init:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
